name: Deploy Synthetic Monitors

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      # Restores terraform.tfstate from previous workflow runs
      - name: Restore Terraform State
        uses: actions/cache@v4
        with:
          path: |
            .terraform/
            terraform.tfstate
            terraform.tfstate.backup
          key: terraform-state-${{ github.run_id }}
          restore-keys: |
            terraform-state-

      - name: Terraform Init
        run: terraform init
        env:
          TF_VAR_new_relic_account_id: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
          TF_VAR_new_relic_api_key: ${{ secrets.NEW_RELIC_API_KEY }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_new_relic_account_id: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
          TF_VAR_new_relic_api_key: ${{ secrets.NEW_RELIC_API_KEY }}
